spring.application.name=ivanaapi1
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url= jdbc:postgresql://localhost:5432/ivanaapi1db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect